### Rest API com Flask

In [1]:
from flask import Flask
import pandas as pd

app = Flask(__name__) 
tabela = pd.read_excel("Vendas - Dez.xlsx")

@app.route("/")
def faturamento():
    dic_faturamento = float(tabela["Valor Final"].sum())
    return {"faturamento": dic_faturamento}

@app.route("/vendas/produtos")
def vendas_produtos():
    tabela_vendas_produtos = tabela[["Produto", "Valor Final"]].groupby("Produto").sum()
    dic_vendas_produtos = tabela_vendas_produtos.to_dict()
    return dic_vendas_produtos

@app.route("/vendas/produtos/<produto>")
def fat_produto(produto):
    tabela_vendas_produtos = tabela[["Produto", "Valor Final"]].groupby("Produto").sum()
    if produto in tabela_vendas_produtos.index:
        vendas_produto = tabela_vendas_produtos.loc[produto]
        dic_vendas_produto = vendas_produto.to_dict()
        return dic_vendas_produto
    else:
        return {produto: "Inexistente"}

app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [09/Jun/2022 01:46:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [09/Jun/2022 01:46:41] "GET /vendas/produtos/Camisa HTTP/1.1" 200 -

In [3]:
# Somente para visualizar as informações da tabela.

tabela = pd.read_excel('Vendas - Dez.xlsx')
tabela

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65014,2019-12-01,Shopping Morumbi,Sunga Listrado,5,114,570
1,65014,2019-12-01,Shopping Morumbi,Casaco Listrado,1,269,269
2,65016,2019-12-01,Iguatemi Campinas,Sapato Listrado,2,363,726
3,65016,2019-12-01,Iguatemi Campinas,Casaco,1,250,250
4,65017,2019-12-01,Shopping SP Market,Gorro Liso,3,92,276
...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266